
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SwingAndSlideAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SwingAndSlideAddonDeed();
			}
		}

		[ Constructable ]
		public SwingAndSlideAddon()
		{



			AddComplexComponent( (BaseAddon) this, 322, -2, 1, 20, 1118, -1, "swing", 1);// 1
			AddComplexComponent( (BaseAddon) this, 322, -1, 1, 20, 1118, -1, "swing", 1);// 2
			AddComplexComponent( (BaseAddon) this, 322, 0, 1, 20, 1118, -1, "swing", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4706, -1, 1, 16, 0, -1, "swing", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4706, 1, 1, 10, 0, -1, "swing", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4706, 0, 0, 0, 0, -1, "swing", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4706, 0, 0, 3, 0, -1, "swing", 1);// 7
			AddComplexComponent( (BaseAddon) this, 4706, -1, 1, 9, 0, -1, "swing", 1);// 8
			AddComplexComponent( (BaseAddon) this, 4706, -1, 1, 9, 0, -1, "swing", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2919, -1, 1, 0, 1118, -1, "swing", 1);// 10
			AddComplexComponent( (BaseAddon) this, 38955, -3, 1, 0, 0, -1, "swing", 1);// 11
			AddComplexComponent( (BaseAddon) this, 38954, -3, 2, 0, 0, -1, "swing", 1);// 12
			AddComplexComponent( (BaseAddon) this, 38956, -3, 0, 0, 0, -1, "swing", 1);// 13
			AddComplexComponent( (BaseAddon) this, 38951, 1, 1, 0, 0, -1, "swing", 1);// 14
			AddComplexComponent( (BaseAddon) this, 38952, 1, 0, 0, 0, -1, "swing", 1);// 15
			AddComplexComponent( (BaseAddon) this, 38950, 1, 2, 0, 0, -1, "swing", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2919, 0, 1, 0, 1118, -1, "swing", 1);// 17
			AddComplexComponent( (BaseAddon) this, 322, 1, 1, 20, 1118, -1, "swing", 1);// 18
			AddComplexComponent( (BaseAddon) this, 323, -2, 1, 20, 1118, -1, "swing", 1);// 19
			AddComplexComponent( (BaseAddon) this, 323, -2, 2, 20, 1118, -1, "swing", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2913, -2, 0, 0, 1118, -1, "swing", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2913, -2, 1, 0, 1118, -1, "swing", 1);// 22
			AddComplexComponent( (BaseAddon) this, 4706, -2, 0, 1, 0, -1, "swing", 1);// 23
			AddComplexComponent( (BaseAddon) this, 4706, -2, 0, 1, 0, -1, "swing", 1);// 24
			AddComplexComponent( (BaseAddon) this, 4706, -2, 1, 6, 0, -1, "swing", 1);// 25
			AddComplexComponent( (BaseAddon) this, 4706, -3, 0, 0, 0, -1, "swing", 1);// 26
			AddComplexComponent( (BaseAddon) this, 4706, -3, -1, 0, 0, -1, "swing", 1);// 27
			AddComplexComponent( (BaseAddon) this, 4706, -3, -1, 3, 0, -1, "swing", 1);// 28
			AddComplexComponent( (BaseAddon) this, 609, 2, 2, 0, 2500, -1, "slide", 1);// 29
			AddComplexComponent( (BaseAddon) this, 38950, 3, 2, 0, 0, -1, "swing", 1);// 30
			AddComplexComponent( (BaseAddon) this, 38951, 3, 1, 0, 0, -1, "swing", 1);// 31
			AddComplexComponent( (BaseAddon) this, 38952, 3, 0, 0, 0, -1, "swing", 1);// 32
			AddComplexComponent( (BaseAddon) this, 38951, 3, -1, 0, 0, -1, "swing", 1);// 33
			AddComplexComponent( (BaseAddon) this, 38950, 3, 0, 0, 0, -1, "swing", 1);// 34
			AddComplexComponent( (BaseAddon) this, 38952, 3, -2, 0, 0, -1, "swing", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1288, 2, 0, 22, 1118, -1, "swing", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1288, 2, 1, 22, 1118, -1, "swing", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1285, 3, 1, 22, 1118, -1, "swing", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1285, 3, 0, 22, 1118, -1, "swing", 1);// 39
			AddComplexComponent( (BaseAddon) this, 322, 2, -1, 22, 1118, -1, "swing", 1);// 40
			AddComplexComponent( (BaseAddon) this, 322, 3, -1, 22, 1118, -1, "swing", 1);// 41
			AddComplexComponent( (BaseAddon) this, 609, 3, 2, 0, 2500, -1, "slide", 1);// 42
			AddComplexComponent( (BaseAddon) this, 323, 1, 0, 22, 1118, -1, "swing", 1);// 43
			AddComplexComponent( (BaseAddon) this, 323, 1, 1, 22, 1118, -1, "swing", 1);// 44
			AddComplexComponent( (BaseAddon) this, 324, 1, -1, 22, 1118, -1, "swing", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2214, 4, 0, 2, 0, -1, "ladder", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2214, 4, 1, 0, 0, -1, "ladder", 1);// 47

		}

		public SwingAndSlideAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SwingAndSlideAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SwingAndSlideAddon();
			}
		}

		[Constructable]
		public SwingAndSlideAddonDeed()
		{
			Name = "SwingAndSlide";
		}

		public SwingAndSlideAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}