
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GoreFireplaceAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7135, 0, -1, 1}, {13848, -3, -2, 1}, {13883, -2, -2, 1}// 3	13	24	
			, {7135, -2, -1, 1}, {7134, -1, -1, 1}, {7137, -1, -1, 3}// 25	26	44	
			, {13883, -1, -2, 1}, {2420, -1, 0, 5}, {2541, 0, 0, 7}// 47	50	58	
			, {6929, -2, 1, 1}, {6930, -2, 1, 2}, {6660, -2, 2, 7}// 59	60	61	
			, {6658, 3, 0, 7}// 62	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GoreFireplaceAddonDeed();
			}
		}

		[ Constructable ]
		public GoreFireplaceAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 13879, 0, 0, 1, 0, -1, "Gore Fireplace", 1);// 1
			AddComplexComponent( (BaseAddon) this, 13879, -1, 0, 1, 0, -1, "Gore Fireplace", 1);// 2
			AddComplexComponent( (BaseAddon) this, 13852, 2, -1, 1, 1102, -1, "Gore Fireplace", 1);// 4
			AddComplexComponent( (BaseAddon) this, 13854, 2, 1, 1, 1102, -1, "Gore Fireplace", 1);// 5
			AddComplexComponent( (BaseAddon) this, 13852, -1, -2, 1, 1102, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 13883, 1, -2, 1, 0, -1, "Gore Fireplace", 1);// 7
			AddComplexComponent( (BaseAddon) this, 13852, -1, 1, 1, 1102, -1, "Gore Fireplace", 1);// 8
			AddComplexComponent( (BaseAddon) this, 13852, 0, 1, 1, 1102, -1, "Gore Fireplace", 1);// 9
			AddComplexComponent( (BaseAddon) this, 13880, -3, 0, 1, 0, -1, "Gore Fireplace", 1);// 10
			AddComplexComponent( (BaseAddon) this, 13852, 1, 1, 1, 1102, -1, "Gore Fireplace", 1);// 11
			AddComplexComponent( (BaseAddon) this, 13852, 1, -2, 1, 1102, -1, "Gore Fireplace", 1);// 12
			AddComplexComponent( (BaseAddon) this, 13852, 1, -1, 1, 1102, -1, "Gore Fireplace", 1);// 14
			AddComplexComponent( (BaseAddon) this, 13852, 0, -2, 1, 1102, -1, "Gore Fireplace", 1);// 15
			AddComplexComponent( (BaseAddon) this, 13852, 0, 0, 1, 1102, -1, "Gore Fireplace", 1);// 16
			AddComplexComponent( (BaseAddon) this, 13852, -3, -2, 1, 1102, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 13852, 0, -1, 1, 1102, -1, "Gore Fireplace", 1);// 18
			AddComplexComponent( (BaseAddon) this, 13852, -3, -1, 1, 1102, -1, "Gore Fireplace", 1);// 19
			AddComplexComponent( (BaseAddon) this, 13852, -2, 1, 1, 1102, -1, "Gore Fireplace", 1);// 20
			AddComplexComponent( (BaseAddon) this, 13852, -2, -2, 1, 1102, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 13852, 2, 0, 1, 1102, -1, "Gore Fireplace", 1);// 22
			AddComplexComponent( (BaseAddon) this, 13881, -2, 0, 1, 0, -1, "Gore Fireplace", 1);// 23
			AddComplexComponent( (BaseAddon) this, 13880, 1, -1, 1, 0, -1, "Gore Fireplace", 1);// 27
			AddComplexComponent( (BaseAddon) this, 13852, 1, 0, 1, 1102, -1, "Gore Fireplace", 1);// 28
			AddComplexComponent( (BaseAddon) this, 13854, -3, 1, 1, 1102, -1, "Gore Fireplace", 1);// 29
			AddComplexComponent( (BaseAddon) this, 13852, -1, 0, 1, 1102, -1, "Gore Fireplace", 1);// 30
			AddComplexComponent( (BaseAddon) this, 13852, -1, -1, 1, 1102, -1, "Gore Fireplace", 1);// 31
			AddComplexComponent( (BaseAddon) this, 13852, -2, 0, 1, 1102, -1, "Gore Fireplace", 1);// 32
			AddComplexComponent( (BaseAddon) this, 6573, -2, -1, 6, 0, 1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 13883, 0, -2, 1, 0, -1, "Gore Fireplace", 1);// 34
			AddComplexComponent( (BaseAddon) this, 13861, -2, -1, 11, 0, -1, "Gore Fireplace", 1);// 35
			AddComplexComponent( (BaseAddon) this, 13859, -1, -1, 11, 0, -1, "Gore Fireplace", 1);// 36
			AddComplexComponent( (BaseAddon) this, 13842, 2, -1, 1, 0, -1, "Gore Fireplace", 1);// 37
			AddComplexComponent( (BaseAddon) this, 6572, 0, -1, 6, 0, 1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 13852, -3, 0, 1, 1102, -1, "Gore Fireplace", 1);// 39
			AddComplexComponent( (BaseAddon) this, 13852, -2, -1, 1, 1102, -1, "Gore Fireplace", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2416, -1, 0, 13, 38, -1, "Blood Stew", 1);// 41
			AddComplexComponent( (BaseAddon) this, 6574, -1, -1, 6, 0, 1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 13859, 1, -1, 11, 0, -1, "Gore Fireplace", 1);// 43
			AddComplexComponent( (BaseAddon) this, 6572, -2, 0, 1, 0, 1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 13861, 0, -1, 11, 0, -1, "Gore Fireplace", 1);// 46
			AddComplexComponent( (BaseAddon) this, 3561, -1, -1, 1, 0, 1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 3561, -2, -1, 0, 0, 1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 13852, 2, -2, 1, 1102, -1, "Gore Fireplace", 1);// 51
			AddComplexComponent( (BaseAddon) this, 13845, 1, 0, 1, 0, -1, "Gore Fireplace", 1);// 52
			AddComplexComponent( (BaseAddon) this, 4651, 1, 1, 1, 38, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 4650, -2, 1, 1, 38, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 13842, -3, 1, 1, 0, -1, "Gore Fireplace", 1);// 55
			AddComplexComponent( (BaseAddon) this, 13880, -3, -1, 1, 0, -1, "Gore Fireplace", 1);// 56
			AddComplexComponent( (BaseAddon) this, 2416, 0, 0, 13, 1369, -1, "Slime Stew", 1);// 57

		}

		public GoreFireplaceAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GoreFireplaceAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GoreFireplaceAddon();
			}
		}

		[Constructable]
		public GoreFireplaceAddonDeed()
		{
			Name = "GoreFireplace";
		}

		public GoreFireplaceAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}