
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Desk6Addon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Desk6AddonDeed();
			}
		}

		[ Constructable ]
		public Desk6Addon()
		{



			AddComplexComponent( (BaseAddon) this, 2947, 0, 1, 0, 1175, -1, "Desk", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2949, -1, 2, 0, 1175, -1, "Desk", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2950, 1, 2, 0, 1175, -1, "Desk", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2950, -1, 1, 0, 1175, -1, "Desk", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2950, 0, 2, 0, 1175, -1, "Desk", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2947, 0, -1, 0, 1175, -1, "Desk", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2950, -1, 0, 0, 1175, -1, "Desk", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2950, -1, -1, 0, 1175, -1, "Desk", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2951, 0, 0, 0, 1175, -1, "Desk", 1);// 9
			AddComplexComponent( (BaseAddon) this, 10648, -1, 2, 3, 1987, -1, "Desk", 1);// 10
			AddComplexComponent( (BaseAddon) this, 10648, 0, 2, 3, 1987, -1, "Desk", 1);// 11
			AddComplexComponent( (BaseAddon) this, 10648, 1, 2, 3, 1987, -1, "Desk", 1);// 12
			AddComplexComponent( (BaseAddon) this, 10645, -2, 2, 3, 1987, -1, "Desk", 1);// 13
			AddComplexComponent( (BaseAddon) this, 10645, -2, 1, 3, 1987, -1, "Desk", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2612, -1, 0, 6, 1987, -1, "Desk", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2612, -1, 0, 14, 1987, -1, "Desk", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2612, -1, 1, 6, 1987, -1, "Desk", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2612, -1, 1, 14, 1987, -1, "Desk", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2612, -1, -1, 6, 1987, -1, "Desk", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2950, 2, 2, 0, 1175, -1, "Desk", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2948, 3, 2, 0, 1175, -1, "Desk", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2947, 3, 0, 0, 1175, -1, "Desk", 1);// 22
			AddComplexComponent( (BaseAddon) this, 10648, 2, 2, 3, 1987, -1, "Desk", 1);// 23
			AddComplexComponent( (BaseAddon) this, 10651, 3, 2, 3, 1987, -1, "Desk", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2950, 2, 0, 0, 1175, -1, "Desk", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2950, 2, 1, 0, 1175, -1, "Desk", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2951, 3, 1, 0, 2109, -1, "Desk", 1);// 27
			AddComplexComponent( (BaseAddon) this, 7802, 3, 1, 3, 1987, -1, "Desk", 1);// 28
			AddComplexComponent( (BaseAddon) this, 7802, 3, 0, 3, 1987, -1, "Desk", 1);// 29
			AddComplexComponent( (BaseAddon) this, 10645, 3, 1, 3, 1987, -1, "Desk", 1);// 30
			AddComplexComponent( (BaseAddon) this, 10645, 3, 0, 3, 1987, -1, "Desk", 1);// 31

		}

		public Desk6Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Desk6AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Desk6Addon();
			}
		}

		[Constructable]
		public Desk6AddonDeed()
		{
			Name = "Desk6";
		}

		public Desk6AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}