
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PilloryEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4734, 1, 2, 0}, {4735, 0, 2, 0}, {4736, -1, 2, 0}// 1	2	3	
			, {4737, -1, 1, 0}, {4738, 0, 1, 0}, {4739, 1, 1, 0}// 4	5	6	
			, {4740, 1, 0, 0}, {4741, 0, 0, 0}, {4742, -1, 0, 0}// 7	8	9	
			, {4743, -1, -1, 0}, {4744, 0, -1, 0}, {4745, 1, -1, 0}// 10	11	12	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PilloryEastAddonDeed();
			}
		}

		[ Constructable ]
		public PilloryEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

        public PilloryEastAddon(Serial serial)
            : base(serial)
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PilloryEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PilloryEastAddon();
			}
		}

		[Constructable]
		public PilloryEastAddonDeed()
		{
            Name = "PilloryEast";
		}

		public PilloryEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}