/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class NewLoveseatNorthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new NewLoveseatNorthAddonDeed();
			}
		}

		[ Constructable ]
		public NewLoveseatNorthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1801 );
			ac.Name = "love seat";
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "love seat";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "love seat";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "love seat";
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "love seat";
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "love seat";
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2916 );
			ac.Hue = 2307;
			ac.Name = "love seat";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2916 );
			ac.Hue = 2307;
			ac.Name = "love seat";
			AddComponent( ac, 1, 1, 0 );

		}

		public NewLoveseatNorthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class NewLoveseatNorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new NewLoveseatNorthAddon();
			}
		}

		[Constructable]
		public NewLoveseatNorthAddonDeed()
		{
			Name = "NewLoveseatNorth";
		}

		public NewLoveseatNorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}