
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmallPondAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6039, 0, 0, 0}, {6045, 1, 0, 0}, {6047, 0, -1, 0}// 1	2	3	
			, {6049, 0, 1, 0}, {6051, -1, 0, 0}, {6053, 1, -1, 0}// 4	5	6	
			, {6055, 1, 1, 0}, {6054, -1, -1, 0}, {6056, -1, 1, 0}// 7	8	9	
			, {4963, -1, -1, 0}, {4964, 0, -1, 0}, {4970, 0, 1, 0}// 10	11	12	
			, {4968, -1, 0, 0}, {4969, 1, 0, 0}, {4971, 1, 1, 0}// 13	14	15	
			, {4972, -1, 1, 0}, {4973, 1, -1, 0}, {3254, -1, 1, 5}// 16	17	18	
			, {3248, 1, 1, 2}, {3251, -1, 1, 0}// 19	20	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmallPondAddonDeed();
			}
		}

		[ Constructable ]
		public SmallPondAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SmallPondAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmallPondAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmallPondAddon();
			}
		}

		[Constructable]
		public SmallPondAddonDeed()
		{
			Name = "a small pond deed";
		}

		public SmallPondAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}