
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class DockEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1997, 1, 2, 6}, {1997, 1, 0, 6}, {1997, 1, 1, 6}// 1	2	3	
			, {1997, 2, 2, 6}, {1997, 2, 1, 6}, {1997, 2, 0, 6}// 4	5	6	
			, {1997, 3, 2, 6}, {1997, 3, 1, 6}, {1997, 3, 0, 6}// 7	8	9	
			, {1997, -3, 2, 6}, {1997, -3, 1, 6}, {1997, -2, 2, 6}// 10	11	12	
			, {1997, -2, 1, 6}, {1997, -1, 2, 6}, {1997, 0, 2, 6}// 13	14	15	
			, {1997, 0, 1, 6}, {1997, -1, 1, 6}, {1997, -3, 0, 6}// 16	17	18	
			, {1997, -2, 0, 6}, {1997, -1, 0, 6}, {1997, 0, 0, 6}// 19	20	21	
			, {1997, -7, 2, 6}, {1997, -7, 0, 6}, {1997, -7, 1, 6}// 22	23	24	
			, {1997, -6, 2, 6}, {1997, -6, 1, 6}, {1997, -6, 0, 6}// 25	26	27	
			, {1997, -5, 1, 6}, {1997, -5, 0, 6}, {1997, -4, 2, 6}// 28	29	30	
			, {1997, -4, 1, 6}, {1997, -4, 0, 6}, {1997, -5, 2, 6}// 31	32	33	
			, {1997, 1, 3, 6}, {1997, 2, 3, 6}, {1997, 3, 3, 6}// 34	35	36	
			, {942, 1, 3, 0}, {1997, -3, 3, 6}, {1997, -2, 3, 6}// 37	38	39	
			, {1997, -1, 3, 6}, {1997, 0, 3, 6}, {942, -3, 3, 0}// 40	41	42	
			, {1997, -7, 3, 6}, {1997, -6, 3, 6}, {1997, -5, 3, 6}// 43	44	45	
			, {1997, -4, 3, 6}, {942, -7, 3, 0}, {3026, 4, -8, 24}// 46	47	48	
			, {1997, 4, 2, 6}, {1997, 4, 1, 6}, {1997, 4, 0, 6}// 49	50	51	
			, {942, 8, -5, 0}, {942, 8, -1, 0}, {1997, 5, 1, 6}// 52	53	54	
			, {1997, 5, -1, 6}, {1997, 5, 2, 6}, {1997, 5, 0, 6}// 55	56	57	
			, {1997, 6, 2, 6}, {1997, 6, 1, 6}, {1997, 6, 0, 6}// 58	59	60	
			, {1997, 6, -1, 6}, {1997, 7, 2, 6}, {1997, 7, 1, 6}// 61	62	63	
			, {1997, 7, -1, 6}, {1997, 8, 2, 6}, {1997, 8, 1, 6}// 64	65	66	
			, {1997, 8, 0, 6}, {1997, 8, -1, 6}, {1997, 7, 0, 6}// 67	68	69	
			, {1997, 4, 3, 6}, {1997, 5, 5, 6}, {1997, 5, 3, 6}// 86	87	88	
			, {1997, 5, 6, 6}, {1997, 5, 4, 6}, {1997, 6, 6, 6}// 89	90	91	
			, {1997, 6, 5, 6}, {1997, 6, 4, 6}, {1997, 6, 3, 6}// 92	93	94	
			, {1997, 7, 6, 6}, {1997, 7, 5, 6}, {1997, 7, 4, 6}// 95	96	97	
			, {1997, 7, 3, 6}, {1997, 8, 6, 6}, {1997, 8, 5, 6}// 98	99	100	
			, {1997, 8, 4, 6}, {1997, 8, 3, 6}, {942, 8, 8, 0}// 101	102	103	
			, {942, 8, 4, 0}, {1997, 6, 8, 6}, {1997, 6, 7, 6}// 104	105	106	
			, {1997, 6, 6, 6}, {1997, 6, 5, 6}, {1997, 7, 8, 6}// 107	108	109	
			, {1997, 7, 6, 6}, {1997, 7, 5, 6}, {1997, 8, 8, 6}// 110	111	112	
			, {1997, 8, 7, 6}, {1997, 8, 6, 6}, {1997, 8, 5, 6}// 113	114	115	
			, {1997, 7, 7, 6}, {1997, 5, 7, 6}, {1997, 5, 5, 6}// 116	117	118	
			, {1997, 5, 8, 6}, {1997, 5, 6, 6}// 119	120	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new DockEastAddonDeed();
			}
		}

		[ Constructable ]
		public DockEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1997, 6, -5, 6, 0, -1, "(8,1997): 0, -1, 0", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1997, 7, -5, 6, 0, -1, "(12,1997): 1, -1, 0", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1997, 8, -5, 6, 0, -1, "(16,1997): 2, -1, 0", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1997, 5, -5, 6, 0, -1, "(2,1997): -1, -1, 0", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1997, 6, -2, 6, 0, -1, "(5,1997): 0, 2, 0", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1997, 7, -2, 6, 0, -1, "(9,1997): 1, 2, 0", 1);// 75
			AddComplexComponent( (BaseAddon) this, 1997, 7, -3, 6, 0, -1, "(10,1997): 1, 1, 0", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1997, 8, -2, 6, 0, -1, "(13,1997): 2, 2, 0", 1);// 77
			AddComplexComponent( (BaseAddon) this, 1997, 8, -3, 6, 0, -1, "(14,1997): 2, 1, 0", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1997, 6, -3, 6, 0, -1, "(6,1997): 0, 1, 0", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1997, 6, -4, 6, 0, -1, "(7,1997): 0, 0, 0", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1997, 7, -4, 6, 0, -1, "(11,1997): 1, 0, 0", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1997, 8, -4, 6, 0, -1, "(15,1997): 2, 0, 0", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1997, 5, -3, 6, 0, -1, "(1,1997): -1, 1, 0", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1997, 5, -2, 6, 0, -1, "(3,1997): -1, 2, 0", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1997, 5, -4, 6, 0, -1, "(4,1997): -1, 0, 0", 1);// 85

		}

		public DockEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class DockEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new DockEastAddon();
			}
		}

		[Constructable]
		public DockEastAddonDeed()
		{
			Name = "Dock (East)";
		}

		public DockEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}