//Scripted By- Milva
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;

namespace Server.Gumps
{
    public class DeathsReaperQuestGump : Gump
     { 
      public static void Initialize() 
      {
          CommandSystem.Register("DeathsReaperQuestGump", AccessLevel.GameMaster, new CommandEventHandler(DeathsReaperQuestGump_OnCommand)); 
      } 

      private static void DeathsReaperQuestGump_OnCommand( CommandEventArgs e ) 
      { 
         e.Mobile.SendGump( new DeathsReaperQuestGump( e.Mobile ) ); 
      } 

      public DeathsReaperQuestGump( Mobile owner ) : base( 50,50 ) 
      { 
                                                 this.Closable=true;
			this.Disposable=true;
			this.Dragable=true;
			this.Resizable=false;

                                                AddPage(0);
			AddImageTiled(13, 9, 378, 433, 2524);
			AddImageTiled(8, 7, 388, 10, 40);
			AddImageTiled(11, 433, 382, 9, 40);
			AddImage(13, 18, 3005, 1152);
			AddImage(389, 17, 3003, 1152);
			AddImage(389, 188, 3003, 1152);
			AddImage(12, 187, 3005, 1152);
			AddImage(64, 35, 1143, 47);
			AddTextEntry(114, 38, 171, 20, 657, 0, @"  Booo!  Halloween Quest!");
			AddItem(6, 358, 3197);
			AddItem(48, 416, 3179);
			AddItem(343, 20, 7869);
			AddItem(22, 21, 7869);
			AddItem(28, 358, 3197);
			AddItem(42, 67, 3179);
			AddItem(277, 58, 6659);
			AddItem(281, 46, 6664);
			AddItem(19, 73, 3179);
			AddItem(18, 341, 7733);
        

			
            AddHtml(34, 90, 346, 281, "<BODY>" +
      //----------------------/----------------------------------------------/
"<BASEFONT COLOR=Orange>Who are you?<BR><BR>The Deaths Reaper looks at you with death in his eye!!<BR>" +
"<BASEFONT COLOR=Orange>You say your looking for some Halloween excitement?<BR>" +
"<BASEFONT COLOR=Orange>Yumm I can smell death with the crisp autumn air!.<BR>" +
"<BASEFONT COLOR=Orange>Makes my mouth water, just thinking about some human stew!<BR><BR>" +
"<BASEFONT COLOR=Orange>Sadly, I can't slay you today, my Deaths Scythe has been stolen! <BR><BR>" +
"<BASEFONT COLOR=Orange>Rumor is that some Cursed Executioner stole it<BR><BR>" +
"<BASEFONT COLOR=Orange>Bring back my Deaths Scythe and I shall reward you<BR><BR>" +
"<BASEFONT COLOR=Orange>Not only with your life but with my  Gore Fireplace, Great for cooking humans<BR><BR>" +
"<BASEFONT COLOR=Orange>This Executioner was last seen in the Arena-Malas!<BR><BR>" +
"<BASEFONT COLOR=Orange>Hurry Go now! Bring back my Deaths Scythe<BR><BR>" +
                  "</BODY>", false, true);

             AddButton(163, 385, 247, 248, 0, GumpButtonType.Reply, 0);
             
  
//--------------------------------------------------------------------------------------------------------------
   } 

      public override void OnResponse( NetState state, RelayInfo info ) //Function for GumpButtonType.Reply Buttons 
      { 
         Mobile from = state.Mobile; 

         switch ( info.ButtonID ) 
         { 
            case 0: //Case uses the ActionIDs defenied above. Case 0 defenies the actions for the button with the action id 0 
            { 
               //Cancel 
               from.SendMessage( "Please Go And Get My Deaths Scythe." );
               break; 
            } 

         }
      }
     }
}
   

        


    